sudo: false
language: node_js
node_js:
- '0.8'
- '0.10'
- '0.12'
- '4'
- '6'
- '8'
- '9'
matrix:
  fast_finish: true
  allow_failures:
  - node_js: '0.12'
  - node_js: '9'
cache:
  directories:
  - "$HOME/.npm"
  - "$HOME/.yarn-cache"
install:
- eval "$(curl -s https://raw.githubusercontent.com/bevry/awesome-travis/ef794235b7094de5e49fb64e226da032ce135ecd/scripts/node-install.bash)"
before_script:
- eval "$(curl -s https://raw.githubusercontent.com/bevry/awesome-travis/ef794235b7094de5e49fb64e226da032ce135ecd/scripts/node-verify.bash)"
after_success:
- eval "$(curl -s https://raw.githubusercontent.com/bevry/awesome-travis/ef794235b7094de5e49fb64e226da032ce135ecd/scripts/node-publish.bash)"
notifications:
  slack:
    secure: AVhitH5zNBKKMn4BHzismUR+SvY45T4Hgtg2K/YQNUkMJxQQ1tb2HF+urUECIr+I/opx4viuwVUoCjdP+NZ26MvFTrkQuvv7V3y39BxOIHrK2NKwh74duEh7PFhfyNM5jJbFlYUEmMVz+1chRYzSh2dft28m7EyqxYYQbTnUH4Y=
  email:
    recipients:
      secure: V3g2pFkqjAjh8Ho1x8W5ylxGjulo91kbcsEgzUJxyEMm16XJGcSQfy/ocpf0ChW/YJgNSHyUep+bKJliggdO5ymsWj4rmBO6pa3FGqwdIKk2PAMVI98ftk6zDnXDTK0zC3Ju0iOMnc9ZYbKmXo3Ez7HfxC+U2dSV0eCm4atGlrc=
