sudo: false
language: node_js
node_js:
- '0.12'
- '4'
- '6'
- '8'
- '10'
- '12'
- '13'
matrix:
  fast_finish: true
  allow_failures: []
cache: npm
install:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/c91c9d5eef34ecb0e92029667fd5052640225fa3/scripts/node-install.bash)"
before_script:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/c91c9d5eef34ecb0e92029667fd5052640225fa3/scripts/node-verify.bash)"
after_success:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/c91c9d5eef34ecb0e92029667fd5052640225fa3/scripts/surge.bash)"
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/c91c9d5eef34ecb0e92029667fd5052640225fa3/scripts/node-publish.bash)"
notifications:
  email:
    recipients:
      secure: FohkRfTkcLaeyOJDPEwu8knDwrPixq45PSDJYScJqGg2qxCO36IIScDjsoM5YT3Y3xqYnCChMVhY0FrCK4b0XCYXehftKOWhg4k94TC4QR78hazdzwHuIGkjpvkVWKCV+Keg/ExCLyHlD81ZnHrYbxTMbDq+8CZ/SXhdR91oCPM=
